package com.ftn.sbnz.rules.cep;

import com.ftn.sbnz.model.drools.DumpsiteDetectionEvent;
import com.ftn.sbnz.model.drools.Notification;

declare DumpsiteDetectionEvent
    @role(event)
    @timestamp(detectedAt)
end

rule "CEP - Cluster: vise deponija u istoj regiji za 24h"
    when
        $e1 : DumpsiteDetectionEvent($region : region)

        $count : Number(intValue >= 3) from accumulate(
            DumpsiteDetectionEvent(region == $region) over window:time(24h),
            count(1)
        )
    then
        insert(new Notification(
            "ENV_AGENCY",
            "Agencija za zastitu zivotne sredine",
            $e1.getDumpsiteId(),
            "UPOZORENJE: 3+ deponije u regiji " + $region
        ));

        System.out.println("CEP: Klaster u " + $region);
end

rule "CEP - Ekoloski rizik: deponija blizu reke"
    when
        $e : DumpsiteDetectionEvent(nearRiver == true)
        not Notification(dumpsiteId == $e.dumpsiteId, type == "CEP_RIVER")
    then
        insert(new Notification("CEP_RIVER", "Inspekcija za vode",
            $e.getDumpsiteId(),
            "CEP: Nova deponija detektovana u blizini reke - hitan ekoloski rizik!"));
        System.out.println("CEP: Deponija blizu reke - " + $e.getDumpsiteId() + " region: " + $e.getRegion());
end

rule "CEP - Ekoloski rizik: deponija blizu naselja"
    when
        $e : DumpsiteDetectionEvent(nearCity == true)
        not Notification(dumpsiteId == $e.dumpsiteId, type == "CEP_CITY")
    then
        insert(new Notification("CEP_CITY", "Lokalna samouprava",
            $e.getDumpsiteId(),
            "CEP: Nova deponija detektovana u blizini naselja - obavestiti stanovnistvo!"));
        System.out.println("CEP: Deponija blizu naselja - " + $e.getDumpsiteId() + " region: " + $e.getRegion());
end